/*вернет дату оплаты и сумму остатка по платежу*/
EXECUTE BLOCK(
RESERVATIONKEY INTEGER =:tkey)
RETURNS(
PAYDATE DATE,
SUMnoPAy NUMERIC(15, 4)
) AS
DECLARE VARIABLE SUMALL NUMERIC(15,4);
DECLARE VARIABLE TOTALPARTSUM NUMERIC(15,4);
DECLARE VARIABLE SUMPAY NUMERIC(15,4);

BEGIN
SUMALL = 0;
TOTALPARTSUM = 0;
SUMPAY = 0;
SUMnoPAy = 0;
    SELECT
      R.USR$SUMALL,
      R.USR$TOTALPARTSUM,
      p.USR$CASHDATE,
      SUM ( P.USR$PAIDSUM )
    FROM
      USR$HT_RESERVATION R
    LEFT JOIN USR$SAN_PAYMENT P  on R.ID = P.USR$PERMITKEY
    WHERE P.USR$PERMITKEY  = :RESERVATIONKEY
    Group by 1,2,3
    INTO :SUMALL, :TOTALPARTSUM, :PAYDATE, :SUMPAY;

    SUMnoPAy = SUMALL;
    
    IF ((SUMPAY<>0) and (SUMALL<>0)) THEN
         SUMnoPAy = SUMALL - SUMPAY;

   SUSPEND;
END

